# This is a basic workflow to help you get started with the GitHub Auto-Release on Commit Action.
# Credit to https://github.com/marketplace/actions/auto-release

name: AutoRelease  # The name of the workflow that will appear in the GitHub Actions UI

# Trigger this workflow whenever there is a push to the main or master branch
on:
  push:
    branches:
      - main
      - master

# Grant this workflow permission to write contents (needed to create a release)
permissions:
  contents: write

jobs:
  # Define a job named 'release'
  release:
    # Use an Ubuntu runner for executing the job
    runs-on: ubuntu-24.04

    # Define the sequence of steps for this job
    steps:
      # Step 1: Check out the code from the repository
      - uses: actions/checkout@v4

      # Step 2: Use the Auto Release GitHub Action
      - uses: CupOfTea696/gh-action-auto-release@v1.0.2
        with:
          title: "Release: $version"         # Title for the GitHub release (uses the captured version)
          tag: "v$version"                   # Git tag to be created (e.g., v1.2)
          draft: false                       # If true, creates the release as a draft
          regex: '/^Release: (?<version>[0-9]+\.[0-9]+)/i'  
          # Regex to match a release version string from the commit message (e.g., "Release: 1.2")
          # - Must start at the beginning of a line
          # - Captures version number in a named group "version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auth token to interact with the GitHub API
